version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: .
    container_name: mockbox-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mockbox-network

  # Redis for caching and session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: mockbox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mockbox-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: mockbox-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mockbox-network

volumes:
  redis_data:

networks:
  mockbox-network:
    driver: bridge
